### ISSUE TITLE
As a user, I should be able to see a map, centred on myself.

### ISSUE THREAD

**Issue by benoitknuchel** [LaFrimousse/SwengProject#3]

**Comment by benoitknuchel** [comment]
Hi @dialexo ,
We have this problem where the google map works on Simon's computer but doesn't show on mine. It just let a white screen with google logo.
I "git pull" 'ed the project that is working for Simon, so we have the exact same code.
And when I create a google map project on my own (so I generate a new API key), the map is there and works perfectly.
I also tried different solutions found on StackOverflow but none of them worked out.

Do you have any idea how to fix this or from where it could come from ?

Thank you

**Comment by dialexo** [comment]
Hi @benoitknuchel ,
Do you have a screenshot of this bug ?
I would have said that it looks like a rendering issue or missing google services, however the fact that it works in a different code kinda rules them out. 
Do you have the same emulator API version, system image, emulated device, etc. ? Does the bug also affect real phone hardware ?

**Comment by benoitknuchel** [comment]
![whitemap](https://user-images.githubusercontent.com/25926033/46258865-361ed780-c4d1-11e8-8186-eb9de8273591.png)
Yes we use the same emulator with the same parameters. 
When I try the app on my real phone I get the same white screen.

**Comment by dialexo** [comment]
Thanks.

I have tried your code, it looks like something is wrong in the code itself. Google Maps does seem to load correctly, but something probably fails either when checking permissions or retrieving the current location, hence it seems that Maps does not get updated.

So my guess is that either Simon has previously tried a permission check that allows the app to query his location, and removed it, or you're having non-deterministic race events.

I will let you try to debug this on your own, however a few hints from what I can observe :

Your current code flow is quite weird :
- getDeviceLocation is called twice if the permission is granted
- mLocationPermissionGranted is always false when first checked. Then you set it to true when testing for the permission, but mMap.setMyLocationEnabled is never set again, neither is setMyLocationButtonEnabled.
- Your code relies heavily on callbacks. You may be having non-deterministic race conditions, as you also try to execute synchronous code for other parts. Try to stick to one way or the other (usually async), it will also make your code more readable. A few examples : 
Your code is very asymmetric, as successful paths follow synchronous code, while handling errors is mostly done in callbacks. For instance, you create a location request before checking for permissions, and I suppose you're letting an exception telling you that the permission is missing. This is bad practice as the exception was avoidable, but also what happens when the task fails ? You are asking for resolution but nothing is defined afterwards in the async callback. Meanwhile, updateLocationUI is still called synchronously, and since its code is synchronous, so is getDeviceLocation.
In getDeviceLocation, you initialize str (btw why is it an attribute of the activity ?). The toast is shown synchronously at the bottom of the function. But then you set str asynchronously inside your OnSucessListener. As a reminder, this listener is asynchronous, so it may happen any time in the future, even later than when you show your toast with hello.show. So this translates into a race condition : "how" will almost always be shown, except if the callback is undeterministically called before.

These are only a few weird things I've observed, and a mix of these conditions may be producing the bug (with some probability). Of course, I know that the Android ecosystem is obscure, dense and not very well designed, and I understand that it is very hard to use especially for the first time, so please don't discourage yourselves (I'm not blaming you :P ). But I will give you one general advice that will help you code in this jungle : have several other team members (especially those that are not involved in your task) read your code and review it. This will help you find bugs, check that your code is simple enough (they should understand the functions flow in a few reads (not the implementation details though)).

Also, please use the debugger and Log messages to follow your code paths. I've had different toast messages (BTW you shouldn't use toasts for debugging purposes. If you need debug messages, use Log.d and Android Studio's logcat. Also, consider using messages that are more explicit). Also check the values returned by your method calls (and what external providers return to you).

**Comment by benoitknuchel** [comment]
Well, thanks for your quick answers even on a sunday !
It's my first time using Android Studio and it's already frustrating but it seems like it's normal haha... 
And thank you for your advices, we'll try to apply them (especially the debugger one😅) and work more as a team.

**Comment by dialexo** [comment]
No worries. Try to coin the bug source more specifically, and don't hesitate to ask again. 
Also, if you need us to physically have a look at your issue, you can ask us during Friday's exercise / lab sessions.
